import { Montserrat } from 'next/font/google'
import type { Metadata } from 'next'
import Providers from './_sections/providers'
import ToastComponentClient from './_sections/toast-component-client'

import 'react-toastify/dist/ReactToastify.css';
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const montserrat = Montserrat({
  subsets: ['latin'],
  style: [
    'normal',
    'italic'
  ],
  weight: [
    '100',
    '200',
    '300',
    '400',
    '500',
    '600',
    '700',
    '800',
    '900'
  ],
  display: 'swap',
  fallback: [
    'system-ui',
    'arial'
  ],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark'>
      <Providers>
        <body className={`${montserrat.className}`}>
          <div className='bg-default'>
            {children}
          </div>
          <ToastComponentClient />
        </body>
      </Providers>
    </html>
  )
}
